### ISSUE TITLE
Typo `passphrse ` should be `passphrase` in test.js

### ISSUE THREAD

**Issue by grempe** [ilap/slip39-js#14]
Typo in test descriptions (three instances).

https://github.com/ilap/slip39-js/blob/master/test/test.js#L75

**Comment by ilap** [comment]
Thx for contributin. It will be fixed in the next commit.

**Comment by grempe** [comment]
Sorry, not to be nit picky. You closed this but there doesn’t seem to be a commit with the change. 🤔

**Comment by ilap** [comment]
Sorry, I missed it somehow. Anyway, it's fixed now.
