### ISSUE TITLE
Readme could explain how to use it in browser

### ISSUE THREAD

**Issue by 1000i100** [ilap/slip39-js#21]
And... does it work in browser ?

i would like to build a web-app to shamir anything, and using slip39 could be a good way to do it.

**Comment by ilap** [comment]
You can check [this](https://iancoleman.io/slip39/).

**Comment by ilap** [comment]
This is the [github repo for](https://github.com/iancoleman/slip39) that web based example above.

**Comment by 1000i100** [comment]
Thank-you !
